export const projectArray = [
    { title: 'Travel Agency App', 
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate repellat placeat mollitia deserunt magni odit atque ',
        listItem: ["Next.js",'Tailwind css','TypeScript', 'Redux toolkit'] ,
        link:'https://travel-agency-app-iota.vercel.app/' },
    { title: 'Chart JS Demo', 
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate repellat placeat mollitia deserunt magni odit atque ',
        listItem: ["React js",'Tailwind css','getform.io'] ,
        link:'https://chart-js-demo-lilac.vercel.app/' },
    { title: 'E-commerce Single page view', 
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate repellat placeat mollitia deserunt magni odit atque ',
        listItem: ["React js",'Tailwind css','getform.io'] ,
        link:'https://softnio-task-chi.vercel.app/' },
    { title: 'Sky Gears', 
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate repellat placeat mollitia deserunt magni odit atque ',
        listItem: ["React js",'Tailwind css','getform.io'] ,
        link:'https://sky-gears.vercel.app/' },
    { title: 'Burger Builder Project', 
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate repellat placeat mollitia deserunt magni odit atque ',
        listItem: ["React js",'Tailwind css','getform.io'] ,
        link:'https://burger-builder-project.vercel.app/' },
    { title: 'Restaurent Dashboard', 
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate repellat placeat mollitia deserunt magni odit atque ',
        listItem: ["React js",'Tailwind css',] ,
        link:'https://resturent-project-0ee750.netlify.app/' },
    { title: 'Waxom Final Dashboard', 
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate repellat placeat mollitia deserunt magni odit atque ',
        listItem: ["HTML",'CSS ', 'JAVASCRIPT'] ,
        link:'https://waxom-final-project-ce3499.netlify.app/#' },
    { title: 'Veer Project', 
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate repellat placeat mollitia deserunt magni odit atque ',
        listItem: ["React js",'Tailwind css','getform.io'] ,
        link:'https://veer-project-fc22b7.netlify.app/' },
    { title: 'Modern Ecommerce website', 
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate repellat placeat mollitia deserunt magni odit atque ',
        listItem: ["React js",'Tailwind css','getform.io'] ,
        link:'https://github.com/Sarowar786/' },
    { title: 'Modern Ecommerce website', 
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate repellat placeat mollitia deserunt magni odit atque ',
        listItem: ["React js",'Tailwind css','getform.io'] ,
        link:'https://github.com/Sarowar786/' },
    { title: 'Modern Ecommerce website', 
        description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate repellat placeat mollitia deserunt magni odit atque ',
        listItem: ["React js",'Tailwind css','getform.io'] ,
        link:'https://github.com/Sarowar786/' },
    
    
    
]